### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by karankumar-07** [jaysonsantos/captcha-breaker#2]
import math
import os
import re
from PIL import Image
import numpy as np
import glob
from skimage import img_as_float, io
from skimage.color import *
from skimage.restoration import denoise_tv_chambolle
from sklearn import svm, metrics

# Files are named whatever-actualCaptchaTyped.png
confirmed_images_re = re.compile(r'-([a-zA-Z0-9]{6})\.png$')

from matplotlib import pyplot as plt
def load_image(path):
    img = img_as_float(rgb2gray(io.imread(path)))[9:38,10:177]
    img[img != 0] = 1
    return img

def get_letters(img, number=6, avg_size=29):
    for i in range(number):
        start = i * avg_size
        nimg = img.copy()[:,start:start + avg_size]
        width_difference = avg_size - nimg.shape[1]
        if width_difference != 0:
            nimg = np.append(nimg, np.ones((nimg.shape[0], width_difference)), axis=1)
        yield nimg

not_trained_captcha = load_image('/home/kratos/Downloads/151006221038442.png')
fig, ax = plt.subplots(ncols=6)

for i, letter in enumerate(get_letters(not_trained_captcha)):
    ax[i].imshow(letter)

imgs = []
limit_images = 30000
total_to_train = int(limit_images * 0.8)
loaded_images = 0
imageFolderPath = '/home/kratos/Documents/Office/OCR/Captcha Dataset'
imagePath = glob.glob(imageFolderPath + '/*.png')
imgs = np.array( [np.array(Image.open(img).convert('L'), 'f') for img in imagePath] )
print('{} Images'.format(len(imgs)))

letters_image = []
letters_ascii = []
for image in imgs:
    letters = image
    for column, letter_image in enumerate(get_letters(image)):
        letters_image.append(letter_image.flatten())
        letters_ascii.append(letters[column])

model = svm.SVC(C=10, gamma=0.001, probability=False)
model.fit(letters_image[:total_to_train], letters_ascii[:total_to_train])

error : raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (24000, 215)

**Comment by CodeRed1704** [comment]
import math
import os
import re
from PIL import Image
import numpy as np
import glob
from skimage import img_as_float, io
from skimage.color import *
from skimage.restoration import denoise_tv_chambolle
from sklearn import svm, metrics

# Files are named whatever-actualCaptchaTyped.png
confirmed_images_re = re.compile(r'-([a-zA-Z0-9]{6})\.png$')

from matplotlib import pyplot as plt
def load_image(path):
    img = img_as_float(rgb2gray(io.imread(path)))[9:38,10:177]
    img[img != 0] = 1
    return img

def get_letters(img, number=6, avg_size=29):
    for i in range(number):
        start = i * avg_size
        nimg = img.copy()[:,start:start + avg_size]
        width_difference = avg_size - nimg.shape[1]
        if width_difference != 0:
            nimg = np.append(nimg, np.ones((nimg.shape[0], width_difference)), axis=1)
        yield nimg

not_trained_captcha = load_image('/home/kratos/Downloads/151006221038442.png')
fig, ax = plt.subplots(ncols=6)

for i, letter in enumerate(get_letters(not_trained_captcha)):
    ax[i].imshow(letter)

imgs = []
limit_images = 30000
total_to_train = int(limit_images * 0.8)
loaded_images = 0
imageFolderPath = '/home/kratos/Documents/Office/OCR/Captcha Dataset'
imagePath = glob.glob(imageFolderPath + '/*.png')
imgs = np.array( [np.array(Image.open(img).convert('L'), 'f') for img in imagePath] )
print('{} Images'.format(len(imgs)))

letters_image = []
letters_ascii = []
for image in imgs:
    letters = image
    for column, letter_image in enumerate(get_letters(image)):
        letters_image.append(letter_image.flatten())
        letters_ascii.append(letters[column])

model = svm.SVC(C=10, gamma=0.001, probability=False)
model.fit(letters_image[:total_to_train], letters_ascii[:total_to_train])


error : raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (24000, 215)

**Comment by jaysonsantos** [comment]
It is hard to say what is the problem from the pasted code, I would guess that your images differ in size (pixels) between them thus the wrong shape in the matrix
